name: tl
channels:
  - conda-forge
  - pytorch
dependencies:
  - matplotlib=3.4.2
  - gym=0.18.0
  - scikit-learn=0.24.2
  - opencv=4.5.2
  - pytorch=1.7.0
  - torchtext=0.8.0
  - torchvision=0.8.1
  - pytorch-lightning=1.3.1
  - tqdm=4.60.0
  - wandb=0.10.30
  - jupyter=1.0.0
  - pandas=1.2.4
  - pip=21.1.1
  - pip
  - pip:
    - dataclasses==0.6
    - pytorch-lightning-bolts==0.3.2
    - torchsummary==1.5.1

