name: tl
channels:
  - conda-forge
  - pytorch
dependencies:
  - matplotlib
  - gym
  - scikit-learn
  - opencv
  - pytorch
  - torchtext
  - torchvision
  - pytorch-lightning
  - tqdm
  - opencv
  - wandb
  - jupyter
  - pandas
  - pip
  - pip: 
    - pytorch-lightning-bolts
    - torchsummary
    #- opencv-python

